// src/app/api/pdf/[id]/route.ts
import { NextResponse } from "next/server";
import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";
import { Resend } from "resend";
import { env } from "process";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: resumeId } = await params;

  const protocol = process.env.NODE_ENV === "development" ? "http" : "https";
  const host = request.headers.get("host");
  const printUrl = `${protocol}://${host}/resume/${resumeId}?print=true`;
  const isDev = process.env.NODE_ENV === "development";
  
  const resend = new Resend(env.RESEND_TOKEN);

  let browser;

  try {
    browser = await puppeteer.launch({
      args: isDev ? [] : chromium.args,
      executablePath: isDev
        ? "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
        : await chromium.executablePath(),
      headless: isDev ? "shell" : true, // Use "shell" for newer Puppeteer versions
    });

    const page = await browser.newPage();

    await page.setViewport({
      width: 800,
      height: 1132,
    });

    await page.goto(printUrl, {
      waitUntil: "networkidle0",
    });

    try {
      await page.waitForSelector(".resume-ready", { timeout: 10000 });
    } catch (e) {
      console.error("Timed out waiting for resume data");
    }

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "0", right: "0", bottom: "0", left: "0" },
      displayHeaderFooter: false,
    });

    await browser.close();

    const { searchParams } = new URL(request.url);
    const targetEmail: string | null = searchParams.get("email");

    const data = await resend.emails.send({
      from: 'Resume Builder <onboarding@resend.dev>',
      to: [targetEmail ?? ""],
      subject: 'Your Professional Resume from Resume Builder',
      html: '<strong>Attached is your professional resume generated by ResumeBuilder.</strong>',
      attachments: [
        {
          filename: 'resume.pdf',
          content: Buffer.from(pdf), // The Puppeteer output
        },
      ],
    });

    // ...existing code...

    return new Response(Buffer.from(pdf), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="resume-${resumeId}.pdf"`,
      },
    });
  } catch (error) {
    console.error("Puppeteer Error:", error);
    if (browser) await browser.close();
    return NextResponse.json(
      { error: "PDF Generation Failed" },
      { status: 500 },
    );
  }
}
